name: LHF/pyLHF release

on:
  release:
    branches:
      - master
  push:
    branches:
      - sharedLHF

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        exclude:
          - os: macos-latest
          - os: windows-latest
            ##TODO: Test with windows-latest and msmpi
    
    steps:
    # Get dependencies
    
    - name: Linux Apt update (${{ matrix.os }} , ${{ matrix.mpi }})
      if:   contains(matrix.os,'ubuntu')
      run:  sudo apt-get update
    
    - name: Get Linux OpenMPI dependencies (${{ matrix.os }})
      if:   contains(matrix.os,'ubuntu')
      run:  sudo apt-get install -y openmpi-bin openmpi-common libopenmpi-dev
      
    - name: Get dependencies (${{ matrix.os }})
      if:   contains(matrix.os,'macos')
      run:  brew install openmpi libomp
               
    - name: Get dependencies (${{ matrix.os }})
      if:   contains(matrix.os,'windows-latest')
      run:  wget https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.2.tar.gz
      
    - name: Windows extract-openmpi 
      if:   contains(matrix.os,'windows-latest')
      run:  tar -xvf ./openmpi-4.0.2.tar.gz
      
    - name: Windows configure-openmpi
      if:   contains(matrix.os,'windows-latest')
      run:  ./openmpi-4.0.2/configure --prefix="/home/${USER}/.openmpi"
      
    - name: Windows install-openmpi
      if:  contains(matrix.os,'windows-latest')
      run: |
          make -j
          sudo make install
          
    
          
    # Checkout v2 : https://github.com/actions/checkout
    - uses: actions/checkout@v2
      
    # Check CMake Version 
    - name: Check CMake (${{ matrix.mpi }})
      run: cmake --version
      
    # Make the project
    - name: cmake
      run: cmake . && make
  
    # Run cmake tests
    - name: ctest
      run: make test

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: pip install --upgrade pip && pip install numpy twine
        
    - name: Build manylinux Python wheels
      if:   runner.os == 'Linux'
      uses: RalfG/python-wheels-manylinux-build@v0.3.3-manylinux2010_x86_64
      with:
        python-versions: 'cp36-cp36m cp37-cp37m'
        build-requirements: 'cython numpy'
        system-packages: 'lrzip-devel zlib-devel'
        pre-build-command: ''
        package-path: 'pyLHF/src'
        pip-wheel-args: '-w ./dist --no-deps'

    - name: Check source files
      if:   runner.os == 'Linux'
      run:  ls pyLHF/src/dist/
        
    - name: Publish wheels to PyPI
      if:   runner.os == 'Linux'
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload dist/*-manylinux*.whl


